ボトムナビゲーションバー作成
shinonome-inc/mobile-hikari-qiita-app pull request #1
Opened 2023-09-15 17:02 UTC by Hikari-Tanaka-pikka

2023-09-30 13:28 UTC, Ryunosuke1114 commented on lib/screen/feed_screen.dart
> +      body: Scaffold(
Scaffoldは二重にする必要はないと思います！

2023-09-30 13:35 UTC, Ryunosuke1114 commented on pubspec.yaml
> +  assets:
最終課題用の画像はこれから増えてくるのでimagesの中でそれぞれの役割ごとにフォルダを増やしてあげてもいいかもですね！
この場合だとimages/tab_iconsみたいな感じでフォルダ増やしてあげればアプリで使う画像が整理されてくると思います！（修正任意です）

2023-09-30 14:57 UTC, Ryunosuke1114 commented on lib/screen/home_root/home_root_body.dart
> +class Body extends ConsumerWidget {
ファイル名とクラス名は一致させた方が良いかと

2024-02-17 01:12 UTC, Hikari-Tanaka-pikka commented on lib/screen/feed_screen.dart
> +      body: Scaffold(
対応しました！

3aacc5cc64fd57bdd8a2b200b00666ff9965b2fa

2024-02-17 01:12 UTC, Hikari-Tanaka-pikka commented on pubspec.yaml
> +  assets:
対応しました！

3aacc5cc64fd57bdd8a2b200b00666ff9965b2fa

2024-02-17 01:12 UTC, Hikari-Tanaka-pikka commented on lib/screen/home_root/home_root_body.dart
> +class Body extends ConsumerWidget {
対応しました！

3aacc5cc64fd57bdd8a2b200b00666ff9965b2fa

2024-02-17 15:25 UTC, iu-yusei commented on lib/screen/home_root/home_root_navigation_bar.dart
> +        border: Border(
## 改善点１： Borderのスタイルについて
- [figma](https://www.figma.com/file/r22atGeJ5LpGwOUbYXXOPw/Mobile-Qiita-App?type=design&node-id=9362-26061&mode=design&t=cbn012zZfhM8xLdU-0)の要件と少しだけスタイルが違うようなので、再確認してみてください！

`現在のUI（iphone15）`

<img width="300" src="https://github.com/shinonome-inc/mobile-hikari-qiita-app/assets/78660150/f22b1c50-7e97-42b0-a29d-019bbbc4d889" src="">

2024-02-17 15:26 UTC, iu-yusei commented on lib/screen/home_root/home_root_navigation_bar.dart
> +class _BottomNavigationBar extends ConsumerWidget {
## [NITS] クラス名とファイル名の不一致
- こちらもファイル名とクラス名を一致させられると良いかもしれません！
修正は任意です！

2024-02-17 15:26 UTC, iu-yusei commented on lib/resource/intl_resource.dart
> +class I18n {
ローカリゼーションを意識したコードが欠けていて、素晴らしいです！

2024-02-17 15:41 UTC, iu-yusei commented on lib/app.dart
> +        home: const Scaffold(body: TopPageScreen(title: "aaa")));
## [NITS] titleプロパティについて
- `lib/screen/top_page_screen.dart`の`TopPageScreen`クラスでは、titleプロパティをrequired propertyとして設定されていますが、ウィジェット内で使用されていないようなので、消してしまっても良いかもしれません！

```dart
class TopPageScreen extends StatelessWidget {
  const TopPageScreen({Key? key, required this.title}) : super(key: key);

  final String title;
```

2024-02-17 15:46 UTC, iu-yusei requested changes
実装お疲れ様です！
FreezedやRiverpodを使いこなせていてすごい！
将来有望ですね！🧑‍💻

ルーティングや、ページ切り替えなどの動作は問題ありませんが、
いくつか気になった点をコメントしたので、確認お願いします！

## 改善点
- [改善点1：Borderのスタイルについて](https://github.com/shinonome-inc/mobile-hikari-qiita-app/pull/1#discussion_r1493356385)

## 修正任意項目
- [[NITS] クラス名とファイル名の不一致](https://github.com/shinonome-inc/mobile-hikari-qiita-app/pull/1#discussion_r1493356543)
- [[NITS] titleプロパティについて](https://github.com/shinonome-inc/mobile-hikari-qiita-app/pull/1#discussion_r1493358710)

2024-02-17 19:36 UTC, Hikari-Tanaka-pikka commented on lib/app.dart
> +        home: const Scaffold(body: TopPageScreen(title: "aaa")));
@iu-yusei 

対応しました！
b046683d8c481246144b929aeee27643f6f5e153

2024-02-17 19:36 UTC, Hikari-Tanaka-pikka commented on lib/screen/home_root/home_root_navigation_bar.dart
> +        border: Border(
@iu-yusei 

対応しました！
b046683d8c481246144b929aeee27643f6f5e153

2024-02-17 22:54 UTC, iu-yusei commented on lib/screen/home_root/home_root_navigation_bar.dart
> +          top: BorderSide(width: 1.0, color: Color.fromRGBO(0, 0, 0, 0.3)),
### [NITS] figmaのスタイルと微妙に異なっています

すごく細かい部分なので、修正は任意です！

`figmaで定義されているスタイル`
<img width="229" alt="image" src="https://github.com/shinonome-inc/mobile-hikari-qiita-app/assets/78660150/0c552a07-6c42-4538-9f4b-2e63ce2be8c2">

offsetのYが-0.5として設定されていることがわかると思います！

これに従って、スタイルを定義すると、下記のようになります！


`widthを使う場合`
```dart
decoration: const BoxDecoration(
        border: Border(
          top: BorderSide(width: 0.5, color: Color.fromRGBO(0, 0, 0, 0.3)),
        ),
      ),
```

`offsetを使う場合`
```dart
    decoration: const BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromRGBO(0, 0, 0, 0.3),
            offset: Offset(0, -0.5),
            blurRadius: 0,
          ),
        ],
      ),
```

[IMO] figmaでのUI設計と近いので、Offsetを使ったアプローチの方が好ましいです。


ご経験がお有りで、既に承知のことと思いますが、
エンジニアにとって「要件通りに実装できるか」は重要な評価ポイントの１つになります！
そのため、レビュワーはこの辺りを結構注視しています👀

Hikariさんが、さらにより良いエンジニアとして成長するためにも、
今後は、こういった細かい部分にも気を配ってみてください✨

2024-02-17 22:57 UTC, iu-yusei approved these changes
LGTMです🎉

すごく細かい部分ですが、少し気になった点があったのでコメントしました！

2024-02-18 00:22 UTC, merged